
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * BuyerMenu Frame so the user can see all the available properties
 * @author Pierre-Louis
 */
public class BuyerMenu extends javax.swing.JFrame {

    private Agence agence;
    private Buyer buyer;
    private ArrayList<JLabel> arraylistLabel = new ArrayList<>();
    private ArrayList<JButton> arraylistBook = new ArrayList<>();

    /**
     * Constructor uses a buyer and agence to link everything, used to display only the correct number of labels and buttons
     * @param agence
     * @param buyer
     */
    public BuyerMenu(Agence agence, Buyer buyer) {
        initComponents();
        this.agence = agence;
        this.buyer = buyer;

        // Affichage du nom/prenom/ID du buyer 
        buyerName.setText(buyer.getNom() + " " + buyer.getPrenom());
        String id = String.valueOf(buyer.getID());
        buyerID.setText("ID : " + id);

        // Affichage de toutes les propriétés visibles par le buyer 
        arraylistLabel.add(property1);
        arraylistLabel.add(property2);
        arraylistLabel.add(property3);
        arraylistLabel.add(property4);
        arraylistLabel.add(property5);
        arraylistLabel.add(property6);
        arraylistLabel.add(property7);
        arraylistLabel.add(property8);
        arraylistLabel.add(property9);
        arraylistLabel.add(property10);

        for (int i = 0; i < agence.getArraylistProperty().size(); ++i) {
            arraylistLabel.get(i).setText("<html> Property " + (i + 1) + "<br>" + "Adress : " + agence.getArraylistProperty().get(i).getAdress()
                    + "<br>" + "Type : " + agence.getArraylistProperty().get(i).getType()
                    + "<br>" + "Size : " + agence.getArraylistProperty().get(i).getSize() + "m2"
                    + "<br>" + "Number of bedrooms : " + agence.getArraylistProperty().get(i).getBedrooms()
                    + "<br>" + "Price : " + agence.getArraylistProperty().get(i).getPrice() + " euros"
                    + "<br>" + "ID : " + agence.getArraylistProperty().get(i).getID()
                    + "<br>" + "Owner : " + agence.getArraylistProperty().get(i).getProprio());
        }

        for (int j = agence.getArraylistProperty().size(); j < arraylistLabel.size(); ++j) {
            arraylistLabel.get(j).setVisible(false);
        }
        
        // Affichage ou non des boutons de réservation 
        arraylistBook.add(reservation1);
        arraylistBook.add(reservation2);
        arraylistBook.add(reservation3);
        arraylistBook.add(reservation4);
        arraylistBook.add(reservation5);
        arraylistBook.add(reservation6);
        arraylistBook.add(reservation7);
        arraylistBook.add(reservation8);
        arraylistBook.add(reservation9);
        arraylistBook.add(reservation10);
        
        for(int j = agence.getArraylistProperty().size(); j < arraylistBook.size(); ++j){
            arraylistBook.get(j).setVisible(false);
        }
        
    }

    /**
     * Constructor without arguments
     */
    public BuyerMenu() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        buyerName = new javax.swing.JLabel();
        buyerID = new javax.swing.JLabel();
        property1 = new javax.swing.JLabel();
        property2 = new javax.swing.JLabel();
        property3 = new javax.swing.JLabel();
        property5 = new javax.swing.JLabel();
        property4 = new javax.swing.JLabel();
        property7 = new javax.swing.JLabel();
        property6 = new javax.swing.JLabel();
        property8 = new javax.swing.JLabel();
        property9 = new javax.swing.JLabel();
        property10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        reservation1 = new javax.swing.JButton();
        reservation2 = new javax.swing.JButton();
        reservation3 = new javax.swing.JButton();
        reservation4 = new javax.swing.JButton();
        reservation5 = new javax.swing.JButton();
        reservation6 = new javax.swing.JButton();
        reservation7 = new javax.swing.JButton();
        reservation8 = new javax.swing.JButton();
        reservation9 = new javax.swing.JButton();
        reservation10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buyerName.setText("jLabel1");

        buyerID.setText("jLabel1");

        property1.setText("jLabel1");

        property2.setText("jLabel1");

        property3.setText("jLabel1");

        property5.setText("jLabel1");

        property4.setText("jLabel1");

        property7.setText("jLabel1");

        property6.setText("jLabel1");

        property8.setText("jLabel1");

        property9.setText("jLabel1");

        property10.setText("jLabel1");

        jButton1.setText("Go back to Identification");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        reservation1.setText("Book a visit");
        reservation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservation1ActionPerformed(evt);
            }
        });

        reservation2.setText("Book a visit");
        reservation2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservation2ActionPerformed(evt);
            }
        });

        reservation3.setText("Book a visit");
        reservation3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservation3ActionPerformed(evt);
            }
        });

        reservation4.setText("Book a visit");
        reservation4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservation4ActionPerformed(evt);
            }
        });

        reservation5.setText("Book a visit");
        reservation5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservation5ActionPerformed(evt);
            }
        });

        reservation6.setText("Book a visit");
        reservation6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservation6ActionPerformed(evt);
            }
        });

        reservation7.setText("Book a visit");
        reservation7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservation7ActionPerformed(evt);
            }
        });

        reservation8.setText("Book a visit");
        reservation8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservation8ActionPerformed(evt);
            }
        });

        reservation9.setText("Book a visit");
        reservation9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservation9ActionPerformed(evt);
            }
        });

        reservation10.setText("Book a visit");
        reservation10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservation10ActionPerformed(evt);
            }
        });

        jLabel1.setText("Buyers' Menu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(property7, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(property10, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(property9, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(property8, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(property6, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(property4, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(property5, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(property3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(property2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(property1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(buyerID, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(jLabel1))
                            .addComponent(buyerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(157, 157, 157)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reservation2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservation1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservation3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservation4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservation5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservation6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservation7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservation8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservation9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservation10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buyerName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buyerID)
                            .addComponent(jLabel1)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(property1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservation1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(property2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservation2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(property3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservation3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(property4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservation4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(property5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservation5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(property6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservation6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(property7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservation7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(property8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservation8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(property9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservation9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(property10, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservation10))
                .addGap(102, 102, 102))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2097, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Identification identification = new Identification(agence);
        identification.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reservation9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservation9ActionPerformed
        BookAVisit bookAVisit = new BookAVisit(agence, agence.getArraylistProperty().get(8), buyer);
        bookAVisit.setVisible(true);
        this.dispose();    }//GEN-LAST:event_reservation9ActionPerformed

    private void reservation10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservation10ActionPerformed
        BookAVisit bookAVisit = new BookAVisit(agence, agence.getArraylistProperty().get(9), buyer);
        bookAVisit.setVisible(true);
        this.dispose();    }//GEN-LAST:event_reservation10ActionPerformed

    private void reservation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservation1ActionPerformed
        BookAVisit bookAVisit = new BookAVisit(agence, agence.getArraylistProperty().get(0), buyer);
        bookAVisit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reservation1ActionPerformed

    private void reservation2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservation2ActionPerformed
        BookAVisit bookAVisit = new BookAVisit(agence, agence.getArraylistProperty().get(1), buyer);
        bookAVisit.setVisible(true);
        this.dispose();    }//GEN-LAST:event_reservation2ActionPerformed

    private void reservation3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservation3ActionPerformed
        BookAVisit bookAVisit = new BookAVisit(agence, agence.getArraylistProperty().get(2), buyer);
        bookAVisit.setVisible(true);
        this.dispose();    }//GEN-LAST:event_reservation3ActionPerformed

    private void reservation4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservation4ActionPerformed
        BookAVisit bookAVisit = new BookAVisit(agence, agence.getArraylistProperty().get(3), buyer);
        bookAVisit.setVisible(true);
        this.dispose();    }//GEN-LAST:event_reservation4ActionPerformed

    private void reservation5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservation5ActionPerformed
        BookAVisit bookAVisit = new BookAVisit(agence, agence.getArraylistProperty().get(4), buyer);
        bookAVisit.setVisible(true);
        this.dispose();    }//GEN-LAST:event_reservation5ActionPerformed

    private void reservation6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservation6ActionPerformed
        BookAVisit bookAVisit = new BookAVisit(agence, agence.getArraylistProperty().get(5), buyer);
        bookAVisit.setVisible(true);
        this.dispose();    }//GEN-LAST:event_reservation6ActionPerformed

    private void reservation7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservation7ActionPerformed
        BookAVisit bookAVisit = new BookAVisit(agence, agence.getArraylistProperty().get(6), buyer);
        bookAVisit.setVisible(true);
        this.dispose();    }//GEN-LAST:event_reservation7ActionPerformed

    private void reservation8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservation8ActionPerformed
        BookAVisit bookAVisit = new BookAVisit(agence, agence.getArraylistProperty().get(7), buyer);
        bookAVisit.setVisible(true);
        this.dispose();    }//GEN-LAST:event_reservation8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buyerID;
    private javax.swing.JLabel buyerName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel property1;
    private javax.swing.JLabel property10;
    private javax.swing.JLabel property2;
    private javax.swing.JLabel property3;
    private javax.swing.JLabel property4;
    private javax.swing.JLabel property5;
    private javax.swing.JLabel property6;
    private javax.swing.JLabel property7;
    private javax.swing.JLabel property8;
    private javax.swing.JLabel property9;
    private javax.swing.JButton reservation1;
    private javax.swing.JButton reservation10;
    private javax.swing.JButton reservation2;
    private javax.swing.JButton reservation3;
    private javax.swing.JButton reservation4;
    private javax.swing.JButton reservation5;
    private javax.swing.JButton reservation6;
    private javax.swing.JButton reservation7;
    private javax.swing.JButton reservation8;
    private javax.swing.JButton reservation9;
    // End of variables declaration//GEN-END:variables
}
