
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * SellerProperty Frame to show a seller his properties only
 * @author Pierre-Louis
 */
public class SellerProperties extends javax.swing.JFrame {

    private Agence agence; 
    private Seller seller; 
    
    private ArrayList<JLabel> arraylistLabel = new ArrayList<>();
    private ArrayList<JButton> arraylistButton = new ArrayList<>();
    private ArrayList<Property> myProperties = new ArrayList<>(); 

    /**
     * Constructor with a seller argument to see which seller is connected and agence to get all the needed data
     * @param agence
     * @param seller
     */
    public SellerProperties(Agence agence, Seller seller) {
        initComponents();
        this.agence = agence; 
        this.seller = seller; 
        
        arraylistLabel.add(myProperty1);
        arraylistLabel.add(myProperty2);
        arraylistLabel.add(myProperty3);
        arraylistLabel.add(myProperty4);
        arraylistLabel.add(myProperty5);
        arraylistLabel.add(myProperty6);
        arraylistLabel.add(myProperty7);
        
        arraylistButton.add(manage1);
        arraylistButton.add(manage2);
        arraylistButton.add(manage3);
        arraylistButton.add(manage4);
        arraylistButton.add(manage5);
        arraylistButton.add(manage6);
        arraylistButton.add(manage7);

        
        sellerName.setText(seller.getNom() + " " + seller.getPrenom());
        
        String id = String.valueOf(seller.getID());

        sellerID.setText("ID : " + id);
        
        for(int i = 0; i < agence.getArraylistProperty().size(); ++i){
            if(agence.getArraylistProperty().get(i).getProprio().equals(seller.getNom())){
                myProperties.add(agence.getArraylistProperty().get(i));
            }
        }
        for(int j = 0; j < myProperties.size(); j++){
            arraylistLabel.get(j).setText("<html> Property " + (j+1) 
                + "<br>" + "Adress : " + myProperties.get(j).getAdress()
                + "<br>" + "ID : " + myProperties.get(j).getID()
                + "<br>" + "Size :" + myProperties.get(j).getSize() + " square meters"
                + "<br>" + "Price : " + myProperties.get(j).getPrice() + " euros"
                + "<br>" + "Number of bedrooms : " + myProperties.get(j).getBedrooms()
                + "<br>" + "Type : " + myProperties.get(j).getType()
                + "<br>" + "Owner : " + myProperties.get(j).getProprio() + " (you)");
            arraylistLabel.get(j).setVisible(true); 
            arraylistButton.get(j).setVisible(true);
        }
        
        for(int k = myProperties.size(); k < arraylistLabel.size(); ++k){
            arraylistLabel.get(k).setVisible(false);
            arraylistButton.get(k).setVisible(false);
        }
    }

    /**
     * Constructor without arguments
     */
    public SellerProperties() {
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        sellerName = new javax.swing.JLabel();
        sellerID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        myProperty1 = new javax.swing.JLabel();
        myProperty2 = new javax.swing.JLabel();
        myProperty3 = new javax.swing.JLabel();
        myProperty4 = new javax.swing.JLabel();
        myProperty5 = new javax.swing.JLabel();
        myProperty6 = new javax.swing.JLabel();
        myProperty7 = new javax.swing.JLabel();
        manage1 = new javax.swing.JButton();
        manage2 = new javax.swing.JButton();
        manage3 = new javax.swing.JButton();
        manage4 = new javax.swing.JButton();
        manage5 = new javax.swing.JButton();
        manage6 = new javax.swing.JButton();
        manage7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sellerName.setText("jLabel1");

        sellerID.setText("jLabel1");

        jButton1.setText("Go back to Sellers Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        myProperty1.setText("jLabel1");

        myProperty2.setText("jLabel1");

        myProperty3.setText("jLabel1");

        myProperty4.setText("jLabel1");

        myProperty5.setText("jLabel1");

        myProperty6.setText("jLabel1");

        myProperty7.setText("jLabel1");

        manage1.setText("Manage");
        manage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage1ActionPerformed(evt);
            }
        });

        manage2.setText("Manage");
        manage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage2ActionPerformed(evt);
            }
        });

        manage3.setText("Manage");
        manage3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage3ActionPerformed(evt);
            }
        });

        manage4.setText("Manage");
        manage4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage4ActionPerformed(evt);
            }
        });

        manage5.setText("Manage");
        manage5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage5ActionPerformed(evt);
            }
        });

        manage6.setText("Manage");
        manage6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage6ActionPerformed(evt);
            }
        });

        manage7.setText("Manage");
        manage7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sellerName, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(sellerID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(myProperty5, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                            .addComponent(myProperty4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manage5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manage4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(myProperty7, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manage7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(myProperty6, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manage6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(myProperty2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(myProperty3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(83, 83, 83))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(myProperty1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(95, 95, 95)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manage3, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(manage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sellerName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sellerID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1)))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myProperty1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manage1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myProperty2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manage2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myProperty3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manage3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myProperty4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manage4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myProperty5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manage5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myProperty6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manage6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myProperty7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manage7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 647, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SellerInterface sellerInterface = new SellerInterface(agence, seller); 
        sellerInterface.setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void manage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage1ActionPerformed
        // TODO add your handling code here:
        sellerPropertyManaging sellerPropertyManaging = new sellerPropertyManaging(agence, seller, myProperties.get(0));
        sellerPropertyManaging.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manage1ActionPerformed

    private void manage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage2ActionPerformed
        // TODO add your handling code here:
        sellerPropertyManaging sellerPropertyManaging = new sellerPropertyManaging(agence, seller, myProperties.get(1));
        sellerPropertyManaging.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manage2ActionPerformed

    private void manage3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage3ActionPerformed
        // TODO add your handling code here:
        sellerPropertyManaging sellerPropertyManaging = new sellerPropertyManaging(agence, seller, myProperties.get(2));
        sellerPropertyManaging.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manage3ActionPerformed

    private void manage4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage4ActionPerformed
        // TODO add your handling code here:
        sellerPropertyManaging sellerPropertyManaging = new sellerPropertyManaging(agence, seller, myProperties.get(3));
        sellerPropertyManaging.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manage4ActionPerformed

    private void manage5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage5ActionPerformed
        // TODO add your handling code here:
        sellerPropertyManaging sellerPropertyManaging = new sellerPropertyManaging(agence, seller, myProperties.get(4));
        sellerPropertyManaging.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manage5ActionPerformed

    private void manage6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage6ActionPerformed
        // TODO add your handling code here:
        sellerPropertyManaging sellerPropertyManaging = new sellerPropertyManaging(agence, seller, myProperties.get(5));
        sellerPropertyManaging.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manage6ActionPerformed

    private void manage7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage7ActionPerformed
        // TODO add your handling code here:
        sellerPropertyManaging sellerPropertyManaging = new sellerPropertyManaging(agence, seller, myProperties.get(6));
        sellerPropertyManaging.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manage7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellerProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellerProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellerProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellerProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellerProperties().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manage1;
    private javax.swing.JButton manage2;
    private javax.swing.JButton manage3;
    private javax.swing.JButton manage4;
    private javax.swing.JButton manage5;
    private javax.swing.JButton manage6;
    private javax.swing.JButton manage7;
    private javax.swing.JLabel myProperty1;
    private javax.swing.JLabel myProperty2;
    private javax.swing.JLabel myProperty3;
    private javax.swing.JLabel myProperty4;
    private javax.swing.JLabel myProperty5;
    private javax.swing.JLabel myProperty6;
    private javax.swing.JLabel myProperty7;
    private javax.swing.JLabel sellerID;
    private javax.swing.JLabel sellerName;
    // End of variables declaration//GEN-END:variables
}
